
backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "items"
    label: "Galeria"
    folder: "content/items"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Link do Vinted", name: "link", widget: "string"}
      - {label: "Zdjęcie", name: "image", widget: "image"}
